server:
  port: 8080
spring:
  application:
    name: hm-gateway
  cloud:
    nacos:
      server-addr: 192.168.163.145:8848
    gateway:
      routes:
        - id: item-service                #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://item-service    #匹配后提供服务的路由地址
          predicates:
            - Path=/items/**,/search/**         # 断言，路径相匹配的进行路由

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/addresses/**,/users/**

        - id: trade-service
          uri: lb://trade-service
          predicates:
            - Path=/orders/**

        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**

hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
